USE YDB;

DROP TABLE IF EXISTS [PostComment];
DROP TABLE IF EXISTS [PostReaction];
DROP TABLE IF EXISTS [Post];
DROP TABLE IF EXISTS [Follow];
DROP TABLE IF EXISTS [PasswordSalt];
DROP TABLE IF EXISTS [User];
DROP TABLE IF EXISTS [Profile];

CREATE TABLE [Profile] (
    [Guid] UNIQUEIDENTIFIER PRIMARY KEY,
    [Quote] NVARCHAR(75) NOT NULL,
    [Description] NVARCHAR(500) NOT NULL,
);

CREATE TABLE [User] (
    [Guid] UNIQUEIDENTIFIER PRIMARY KEY,
    [Username] NVARCHAR(100) NOT NULL UNIQUE,
    [Email] NVARCHAR(200) NOT NULL UNIQUE,
    [Password] NVARCHAR(MAX),
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [LastLogin] DATETIME2 DEFAULT NULL,
    [ProfileId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [Profile]([Guid]) ON DELETE CASCADE
);

CREATE TABLE [PasswordSalt] (
    [Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    [UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [User]([Guid]) ON DELETE CASCADE,
    [Salt] NVARCHAR(MAX) NOT NULL
);

CREATE TABLE [Follow] (
    [Follower] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [User]([Guid]),
    [Follows] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [User]([Guid]),
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    PRIMARY KEY ([Follower], [Follows])
);

CREATE TABLE [Post] (
    [Guid] UNIQUEIDENTIFIER PRIMARY KEY,
    [Headline] NVARCHAR(75) NOT NULL,
    [Content] NVARCHAR(1000) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [User]([Guid])
);

CREATE TABLE [PostComment] (
    [Guid] UNIQUEIDENTIFIER PRIMARY KEY,
    [PostId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [Post]([Guid]),
    [Text] NVARCHAR(250) NOT NULL,
    [SuperComment] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [PostComment]([Guid]) DEFAULT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [User]([Guid]),
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE [PostReaction] (
    [UserId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [User]([Guid]),
    [PostId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [Post]([Guid]),
    [Reaction] INT NOT NULL,
    PRIMARY KEY (UserId, PostId)
);